ms-azuretools.vscode-docker
ms-python.python
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cmake-tools
ms-vscode.makefile-tools
eamodio.gitlens
golang.Go
oderwat.indent-rainbow
rust-lang.rust-analyzer
