
# Separate files:
#-------------------
# Docker
# KVM/Qemu


# Basics
curl
wget
vim
zsh
htop
git

# UFW
ufw
gufw

# Python
python
python-pip
python-virtualenv

# DevOps tools
ansible
meld
cmake
make
# neonbench:
clinfo
clang
opencl-icd-loader
opencl-headers

# Cloud clients
python-openstackclient

# Diag/useful tools
neofetch
mesa-demos
smartmontools
lm_sensors

# Basic services / modules
openssh
samba
zfs

# Network testing
nmap
aircrack-ng
netcat

# SDR
rtl_433
gqrx

# Logic analyzer (Sigrok)
pulseview

# Photo CLI tools
perl-image-exiftool

# GUI applications
vlc
okular
chromium
prusa-slicer
blender
hugin
wireshark-qt
libreoffice-still
