
# Separate files:
#-------------------
# Docker
# KVM/Qemu


# Basics
curl
wget
vim
zsh
htop
git

# UFW
ufw
gufw

# Python
python3
python3-pip
python3-venv

# DevOps tools
ansible
meld
cmake
make
# neonbench:
clinfo
clang
ocl-icd-opencl-dev
opencl-clhpp-headers
mesa-opencl-icd

# Cloud clients
python3-openstackclient

# Diag/useful tools
neofetch
mesa-utils
smartmontools
lm-sensors

# Basic services / modules
openssh-server
openssh-client
samba
zfsutils-linux

# Network testing
nmap
aircrack-ng
netcat

# SDR
rtl-433
gqrx-sdr

# Logic analyzer
sigrok

# Photo CLI tools
exiftool

# GUI applications
vlc
okular
chromium
prusa-slicer
blender
hugin
wireshark
libreoffice
