---
- name: Install packages from external file
  hosts: localhost
  become: yes
  tasks:
    - name: Read the list of packages from file
      slurp:
        src: packages.toml
      register: packages_content

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_content['content'] | b64decode | split('\n') | reject('match', '^(#.*)?\\s*$') }}"

