---
- name: Apply Gnome settings from external file
  hosts: localhost
  tasks:
    - name: Read the list of settings from file
      slurp:
        src: lists/gnome-settings-list.toml
      register: settings_content

    - name: Install dconf (with GUI) with apt
      apt:
        name: "dconf-editor"
        state: present

    - name: Apply Gnome settings
      shell: dconf write {{ item.split(' ')[0] }} "{{ item.split(' ', 1)[1] }}"
      loop: "{{ settings_content['content'] | b64decode | split('\n') | reject('match', '^(#.*)?\\s*$') }}"

