---
- name: Install KVM and QEMU on Debian
  hosts: localhost
  become: yes
  tasks:
    - name: Update the apt package index (Debian family)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install KVM and related packages (Debian family)
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
        state: present
      when: ansible_os_family == "Debian"

    - name: Install KVM and related packages (Arch Linux)
      pacman:
        name:
          - qemu-full
          - bridge-utils
        state: present
      when: ansible_os_family == "Archlinux"

    - name: Ensure libvirtd service is enabled and started
      systemd_service:
        name: libvirtd
        enabled: true
        state: restarted

    - name: Get username of user with UID 1000
      shell: "getent passwd 1000 | cut -d: -f1"
      register: username_result
      changed_when: false
      check_mode: no

    - name: Add user with UID 1000 to the libvirt and kvm groups
      user:
        name: "{{ username_result.stdout }}"
        groups: libvirt, kvm
        append: yes
