---
- name: Install packages from external file
  hosts: localhost
  become: yes
  tasks:
    - name: Read the list of packages from file (Debian family)
      slurp:
        src: packages/debian.toml
      register: packages_content
      when: ansible_os_family == "Debian"

    - name: Read the list of packages from file (Arch Linux)
      slurp:
        src: packages/arch.toml
      register: packages_content
      when: ansible_os_family == "Archlinux"

    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_content['content'] | b64decode | split('\n') | reject('match', '^(#.*)?\\s*$') }}"

