---
- name: Install packages from external file
  hosts: localhost
  become: yes
  tasks:
    - name: Read the list of packages from file
      slurp:
        src: snap-packages.toml
      register: packages_content

    - name: Install snap with apt
      apt:
        name: "snapd"
        state: present

    - name: Install packages with snap
      shell: "snap install {{ item }}"
      loop: "{{ packages_content['content'] | b64decode | split('\n') | reject('match', '^(#.*)?\\s*$') }}"

